#!/bin/bash

export NVM_DIR=$HOME/.nvm;
source $NVM_DIR/nvm.sh;

nvm use 14

rm -rf dist
npm run build

cp .firebase dist
cp .firebaserc dist
cp firebase.json dist

cd dist
firebase deploy

google-chrome https://sel-raismes.web.app/