version: "3.8"

services: 
  ui:
    build: ui
    container_name: troc-ui-container
    ports:
      - 5000:5000
    depends_on:
      - backend
    
  backend:
    build: backend
    container_name: troc-backend-container
    command: npm start
    volumes:
      - .:/usr/src/app/
    ports:
      - "5001:5001"
    depends_on:
      - db
  
  pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: emmanuelzakaryan@gmail.com
        PGADMIN_DEFAULT_PASSWORD: postgres
      ports:
        - "5050:80"

  db:
    image: postgres:13-alpine
    container_name: troc-db-container
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
        - POSTGRES_USER=emzak
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=troc-db
        - POSTGRES_HOST=troc-db-host
    

volumes:
  pgdata: 