#!/bin/bash

#jq '.version = $newVal' --arg newVal '777' <<<"$jsonStr"

git add .
git commit -m "'$*'"
git push 

rm -rf dist
npm run build

cp .firebase dist
cp .firebaserc dist
cp firebase.json dist

cd dist
firebase deploy